sudo: required

language: python

python:
    - "3.5"

services:
    - docker

before_install:
    - sudo apt-get update
    - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine

script:
    - cd docker
    - docker-compose run namenode hdfs namenode -format
    - docker-compose up -d
    - docker ps
