sudo: required

language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"

services:
    - docker

before_install:
    - sudo apt-get update
    - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
    - cd docker
    - docker-compose run namenode hdfs namenode -format
    - docker-compose up -d
    - docker ps
    - cd ..

install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION s3fs libhdfs3 -c conda-forge
    - source activate test-environment
    - pip install -r requirements.txt .

script:
    - python examples/joblib_hdfs_multiply.py
    - pytest

after_success:
    - codecov

notifications:
      email: false
